name: ASSIST Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache BSP ephemeris files
        id: cache-bsp
        uses: actions/cache@v4
        with:
          path: data/
          key: bsp-de440-sb441-n16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download ephemeris data
        if: steps.cache-bsp.outputs.cache-hit != 'true'
        working-directory: ./data/
        run: |
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440.bsp
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/planets/Linux/de440/linux_p1550p2650.440
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/small_bodies/asteroids_de441/sb441-n16.bsp

      - name: Build package
        run: pip install .

      - name: Running unittests
        working-directory: /tmp
        env:
          ASSIST_DIR: ${{ github.workspace }}
        run: python -m unittest discover -s "${{ github.workspace }}/assist/test" -v

  integration-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Cache BSP ephemeris files
        id: cache-bsp
        uses: actions/cache@v4
        with:
          path: data/
          key: bsp-de440-sb441-n16

      - name: Install package
        run: pip install ".[server,test]"

      - name: Download ephemeris data
        if: steps.cache-bsp.outputs.cache-hit != 'true'
        working-directory: ./data/
        run: |
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440.bsp
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/small_bodies/asteroids_de441/sb441-n16.bsp

      - name: Verify assist CLI is installed
        run: assist --help

      - name: Run integration tests
        working-directory: /tmp
        env:
          ASSIST_DIR: ${{ github.workspace }}
        run: |
          pytest "${{ github.workspace }}/assist/test/test_query_integration.py" -v
